In [1]:
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

def std_PCA(**argv):
    scaler = MinMaxScaler()
    pca = PCA(**argv)
    pipeline = Pipeline( [ ("scaler", scaler), ("pca", pca)])
    return pipeline

In [3]:
pca = std_PCA(n_components=1)
R2 = pca.fit_transform(A)
R2

array([[-0.32321796],
       [ 0.21758715],
       [ 0.75839225],
       [-0.65276145]])

In [4]:
pca.inverse_transform(R2)

array([[2.39788502e+00, 2.79151117e+03],
       [3.82363542e+00, 5.23184033e+03],
       [5.24938583e+00, 7.67216948e+03],
       [1.52909373e+00, 1.30447902e+03]])

In [2]:
import numpy as np

A = np.array( [
    
    [3, 2000],
    [4, 5000],
    [5, 8000],
    [1, 2000]
], dtype='float'

)

In [1]:
import numpy as np

A = np.array( [
    
    [3, 2000],
    [4, 5000],
    [5, 8000],
    [1, 2000]
], dtype='float'

)

# 归一化

mean = np.mean(A, axis=0)
norm = A - mean
print(norm)


[[-2.50e-01 -2.25e+03]
 [ 7.50e-01  7.50e+02]
 [ 1.75e+00  3.75e+03]
 [-2.25e+00 -2.25e+03]]


In [2]:
# 数据缩放
scope = np.max(norm, axis=0) - np.min(norm, axis=0)
norm = norm / scope

print(norm)

[[-0.0625 -0.375 ]
 [ 0.1875  0.125 ]
 [ 0.4375  0.625 ]
 [-0.5625 -0.375 ]]


In [3]:
# svd  矩阵分解
U, S, V = np.linalg.svd( np.dot(norm.T, norm))


In [4]:
U

array([[-0.65908697, -0.75206673],
       [-0.75206673,  0.65908697]])

In [6]:
U_reduce = U[:, 0].reshape(2, 1)
# 主成分特征矩阵
U_reduce

array([[-0.65908697],
       [-0.75206673]])

In [7]:
R = np.dot(norm, U_reduce)

R

array([[ 0.32321796],
       [-0.21758715],
       [-0.75839225],
       [ 0.65276145]])

In [8]:
Z = np.dot(R, U_reduce.T)
Z

array([[-0.21302875, -0.24308147],
       [ 0.14340886,  0.16364005],
       [ 0.49984646,  0.57036158],
       [-0.43022657, -0.49092016]])

In [9]:
# 数据处理的逆运算

np.multiply(Z, scope) + mean

array([[2.39788502e+00, 2.79151117e+03],
       [3.82363542e+00, 5.23184033e+03],
       [5.24938583e+00, 7.67216948e+03],
       [1.52909373e+00, 1.30447902e+03]])